name: go build and Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      asset_paths: "boofutils-linux-386,boofutils-linux-amd64,boofutils-linux-arm,boofutils-linux-arm64,boofutils-linux-loong64,boofutils-linux-mips,boofutils-linux-mips64,boofutils-linux-mips64le,boofutils-linux-mipsle,boofutils-linux-ppc64,boofutils-linux-ppc64le,boofutils-linux-riscv64,boofutils-linux-s390x,boofutils-windows-386,boofutils-windows-amd64,boofutils-windows-arm,boofutils-windows-arm64"
    steps:
      - name: Update apt packages
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y libasound2-dev pkg-config make gcc

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.4

      - name: Check out code
        uses: actions/checkout@v2

      - name: Build libnms
        run: make nms

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build linux/386
        run: GOOS=linux GOARCH=386 go build -ldflags "-w" -v -o boofutils-linux-386 .
        continue-on-error: true

      - name: Build linux/amd64
        run: GOOS=linux GOARCH=amd64 go build -ldflags "-w" -v -o boofutils-linux-amd64 .
        continue-on-error: true

      - name: Build linux/arm
        run: GOOS=linux GOARCH=arm go build -ldflags "-w" -v -o boofutils-linux-arm .
        continue-on-error: true

      - name: Build linux/arm64
        run: GOOS=linux GOARCH=arm64 go build -ldflags "-w" -v -o boofutils-linux-arm64 .
        continue-on-error: true

      - name: Build linux/loong64
        run: GOOS=linux GOARCH=loong64 go build -ldflags "-w" -v -o boofutils-linux-loong64 .
        continue-on-error: true

      - name: Build linux/mips
        run: GOOS=linux GOARCH=mips go build -ldflags "-w" -v -o boofutils-linux-mips .
        continue-on-error: true

      - name: Build linux/mips64
        run: GOOS=linux GOARCH=mips64 go build -ldflags "-w" -v -o boofutils-linux-mips64 .
        continue-on-error: true

      - name: Build linux/mips64le
        run: GOOS=linux GOARCH=mips64le go build -ldflags "-w" -v -o boofutils-linux-mips64le .
        continue-on-error: true

      - name: Build linux/mipsle
        run: GOOS=linux GOARCH=mipsle go build -ldflags "-w" -v -o boofutils-linux-mipsle .
        continue-on-error: true

      - name: Build linux/ppc64
        run: GOOS=linux GOARCH=ppc64 go build -ldflags "-w" -v -o boofutils-linux-ppc64 .
        continue-on-error: true

      - name: Build linux/ppc64le
        run: GOOS=linux GOARCH=ppc64le go build -ldflags "-w" -v -o boofutils-linux-ppc64le .
        continue-on-error: true

      - name: Build linux/riscv64
        run: GOOS=linux GOARCH=riscv64 go build -ldflags "-w" -v -o boofutils-linux-riscv64 .
        continue-on-error: true

      - name: Build linux/s390x
        run: GOOS=linux GOARCH=s390x go build -ldflags "-w" -v -o boofutils-linux-s390x .
        continue-on-error: true

     - name: Build windows/386
        run: GOOS=windows GOARCH=386 go build -ldflags "-w" -v -o boofutils-windows-386.exe .
        continue-on-error: true

      - name: Build windows/amd64
        run: GOOS=windows GOARCH=amd64 go build -ldflags "-w" -v -o boofutils-windows-amd64.exe .
        continue-on-error: true

      - name: Build windows/arm
        run: GOOS=windows GOARCH=arm go build -ldflags "-w" -v -o boofutils-windows-arm.exe .
        continue-on-error: true

      - name: Build windows/arm64
        run: GOOS=windows GOARCH=arm64 go build -ldflags "-w" -v -o boofutils-windows-arm64.exe .
        continue-on-error: true

      - name: Upload the artifact
        uses: actions/upload-artifact@v3
        with:
          name: boofutils
          path: |
            boofutils-linux-386
            boofutils-linux-amd64
            boofutils-linux-arm
            boofutils-linux-arm64
            boofutils-linux-loong64
            boofutils-linux-mips
            boofutils-linux-mips64
            boofutils-linux-mips64le
            boofutils-linux-mipsle
            boofutils-linux-ppc64
            boofutils-linux-ppc64le
            boofutils-linux-riscv64
            boofutils-linux-s390x
            boofutils-windows-386.exe
            boofutils-windows-amd64.exe
            boofutils-windows-arm.exe
            boofutils-windows-arm64.exe

  upload:
    name: Upload release
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Delete old release and tag
        uses: dev-drprasad/delete-tag-and-release@v1.0.1
        with:
          delete_release: true
          tag_name: latest_auto
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get artifacts
        uses: actions/download-artifact@v3
        with:
          path: build

      - name: Release to GitHub
        uses: ncipollo/release-action@v1
        with:
            name: Latest Autobuild
            tag: latest_auto
            commit: main
            body: ${{ github.event.head_commit.message }}
            artifacts: |
              build/boofutils/boofutils-linux-386
              build/boofutils/boofutils-linux-amd64
              build/boofutils/boofutils-linux-arm
              build/boofutils/boofutils-linux-arm64
              build/boofutils/boofutils-linux-loong64
              build/boofutils/boofutils-linux-mips
              build/boofutils/boofutils-linux-mips64
              build/boofutils/boofutils-linux-mips64le
              build/boofutils/boofutils-linux-mipsle
              build/boofutils/boofutils-linux-ppc64
              build/boofutils/boofutils-linux-ppc64le
              build/boofutils/boofutils-linux-riscv64
              build/boofutils/boofutils-linux-s390x
              build/boofutils/boofutils-windows-386.exe
              build/boofutils/boofutils-windows-amd64.exe
              build/boofutils/boofutils-windows-arm.exe
              build/boofutils/boofutils-windows-arm64.exe
            prerelease: true
