name: Go Build and Pre-release

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      asset_paths: "boofutils-windows-386,boofutils-windows-amd64,boofutils-linux-386,boofutils-linux-amd64"
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.6

      - name: Set up tinygo
        uses: acifani/setup-tinygo@v1
        with:
          tinygo-version: '0.29.0'

      - name: Check out code
        uses: actions/checkout@v2

      - name: Get commit ID
        id: get_commit_id
        run: echo "::set-output name=ID::$(git rev-parse --short HEAD)"

      - name: Get dependencies
        run: go get -v -t -d ./...

      - name: Build windows-386
        run: GOOS=windows GOARCH=386 tinygo build -v -o boofutils-windows-386.exe .

      - name: Build windows-amd64
        run: GOOS=windows GOARCH=amd64 tinygo build -v -o boofutils-windows-amd64.exe .

      - name: Build linux-386
        run: GOOS=linux GOARCH=386 tinygo build -v -o boofutils-linux-386 .

      - name: Build linux-amd64
        run: GOOS=linux GOARCH=amd64 tinygo build -v -o boofutils-linux-amd64 .

      - name: Set asset paths
        id: set-asset-paths
        run: echo "::set-output name=asset_paths::boofutils-windows-386,boofutils-windows-amd64,boofutils-linux-386,boofutils-linux-amd64"

      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo ${GITHUB_REF#refs/*/})

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_commit_id.outputs.ID }}
          release_name: Autobuild - ${{ steps.get_commit_id.outputs.ID }}
          draft: false
          prerelease: true

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./boofutils-windows-386.exe
          asset_name: boofutils-windows-386.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./boofutils-windows-amd64.exe
          asset_name: boofutils-windows-amd64.exe
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./boofutils-linux-386
          asset_name: boofutils-linux-386
          asset_content_type: application/octet-stream

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./boofutils-linux-amd64
          asset_name: boofutils-linux-amd64
          asset_content_type: application/octet-stream
